version: '3'

services: 
    app:
        image: mcr.microsoft.com/vscode/devcontainers/go
        volumes: 
            - ../:/app
        ports: 
            - 5000:5000
            - 3000:3000
        command: tail -f /dev/null
        depends_on:
            - db
    db:
        image: mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: marketplace
